name: 🐞 Bug
description: Report bug release
title: "[BUG-PLATAFORMA-PARCEIRO-JORNADA] Adicione o nome do cenário conforme está no silk"
labels: ["bug-release", "cherry-pick"]
body:
- type: markdown
  attributes:
    value: |
      **PRÉ-REQUISITOS**      
- type: input
  id: Versao-release
  attributes:
    label: Versão da release
    placeholder: ex. [1.20.0]
  validations:
    required: true
- type: input
  id: Modelo-device
  attributes:
    label: Modelo device
    placeholder: ex. [Nexus 5 api 30]
  validations:
    required: true
- type: textarea
  id: passos-execucao
  attributes:
    label: PASSOS PARA EXECUÇÃO
    description: Adicione oa passos até chegar ao erro encontrado no fluxo.
    placeholder: |
       Ex.
         [ Dado que acesso o app
           E estou na home
           Quando tocar no botão [...] 
           Então o app crash ]
  validations:
    required: true
- type: input
  id: resultado-obtido
  attributes:
    label: RESULTADO OBTIDO
    description: Descreva qual o resultado atual da execução que reflete o bug.
  validations:
    required: true
- type: input
  id: resultado-esperado
  attributes:
    label: RESULTADO ESPERADO
    description: Descreva qual deveria ser o resultado esperado.
  validations:
    required: true
- type: input
  id: evidencia
  attributes:
    label: EVIDÊNCIA DO TESTE
    description: Adicione o link do Silk da execução do teste que contenha o print/video do bug.
  validations:
    required: true
- type: textarea
  id: informacao-adicionais
  attributes:
    label: INFORMAÇÕES ADICIONAIS(Opcional)
    description: Adicione informações que considere importante para a resolução do bug.
  validations:
    required: false
