name: 🐞 Bug
description: Report bug release
title: "[BUG-PLATAFORMA-PARCEIRO-JORNADA] <Adicione o nome do cenário conforme está no silk>"
labels: ["bug-release", "cherry-pick"]
body:
- type: input
  id: Versao-release
  attributes:
    label: Versão da release
    placeholder: ex. [1.20.0]
    label: Modelo device
    placeholder: ex. [Nexus 5 api 30]
  validations:
    required: true
- type: input
  id: Modelo-device
  attributes:
    label: Modelo device
    placeholder: ex. [Nexus 5 api 30]
  validations:
    required: true
