name: 🐞 Bug
description: Report bug release
title: "[BUG-PLATAFORMA-PARCEIRO-JORNADA] <Adicione o nome do cenário conforme está no silk>"
labels: ["bug-release", "cherry-pick"]
body:
- type: input
  id: Versao-release
  attributes:
    label: Versão da release
    placeholder: ex. [1.20.0]
  validations:
    required: true
- type: input
  id: Modelo-device
  attributes:
    label: Modelo device
    placeholder: ex. [Nexus 5 api 30]
  validations:
    required: true
- type: textarea
  id: passos-execucao
  attributes:
    label: PASSOS PARA EXECUÇÃO
    description: Adicione oa passos até chegar ao erro encontrado no fluxo.
    placeholder: Ex.| 
          Dado que acesso o app
          E estou na home
          Quando tocar no botão XPTO
          Então o app crash
  validations:
    required: true
